export const REQUEST_USER_LIST_PENDING = 'REQUEST_USER_LIST_PENDING';
export const REQUEST_USER_LIST_SUCCESS = 'REQUEST_USER_LIST_SUCCESS';
export const REQUEST_USER_LIST_FAILED = 'REQUEST_USER_LIST_FAILED'; 



export const REQUEST_SINGLE_USER_PENDING = 'REQUEST_SINGLE_USER_PENDING';
export const REQUEST_SINGLE_USER_SUCCESS = 'REQUEST_SINGLE_USER_SUCCESS';
export const REQUEST_SINGLE_USER_FAILED = 'REQUEST_SINGLE_USER_FAILED'; 